### ISSUE TITLE
Add folders to .gitignore

### ISSUE THREAD

**Issue by moxxiq** [Sherma/4lab#2]
`.idea` and `venv` folders don't need to be included in a git repository. You can create a `requirements.txt` file for modules that you use, also the PyCharm project settings are personal user preference.

**Comment by OlexandrPozden** [comment]
@moxxiq I did not expect to see you here. It is interesting. I agree with you it is a better idea to ignore folders `.idea` and `venv`.

**Comment by OlexandrPozden** [comment]
In a new pull request, this problem is solved
